apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: grpcreplyrules.example.com
spec:
  group: example.com
  names:
    kind: GrpcReplyRule
    listKind: GrpcReplyRuleList
    plural: grpcreplyrules
    singular: grpcreplyrule
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rules:
                  type: array
                  items:
                    type: object
                    properties:
                      token:
                        type: string
                      role:
                        type: string
                      message:
                        type: string

