# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ai_pb2 as ai__pb2


class ReplyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReply = channel.unary_unary(
                '/google.reply.ReplyService/GetReply',
                request_serializer=ai__pb2.ReplyRequest.SerializeToString,
                response_deserializer=ai__pb2.ReplyResponse.FromString,
                )


class ReplyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReply': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReply,
                    request_deserializer=ai__pb2.ReplyRequest.FromString,
                    response_serializer=ai__pb2.ReplyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.reply.ReplyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReplyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.reply.ReplyService/GetReply',
            ai__pb2.ReplyRequest.SerializeToString,
            ai__pb2.ReplyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
